# Generated by Django 5.1.5 on 2025-01-17 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('task_description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('assign_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
